[package]
name = "base_relations_@{ db|snake }@_@{ unified_name }@"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
base_domain = { path = "../../../../base_domain" }
user_defined_types = { path = "../../../../user_defined_types" }
anyhow.workspace = true
async-graphql.workspace = true
async-stream.workspace = true
base64.workspace = true
chrono.workspace = true
ciborium.workspace = true
derive-new.workspace = true
futures.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
utoipa.workspace = true
uuid.workspace = true
validator.workspace = true
@{-"\n"}@
