[package]
name = "_@{ name }@"
version = "0.0.0"
edition = "2024"
publish = false

[features]
js_updater = ["rquickjs"]

[dependencies]
@%- if session %@
_db_session = { path = "../../2_db/session/base" }
@%- endif %@
domain = { path = "../../1_domain" }

actix-web = "4.1"
anyhow.workspace = true
argon2 = "0.5.2"
async-graphql.workspace = true
async-stream = "0.3"
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
derive_more.workspace = true
futures.workspace = true
jsonwebtoken = "9.1.0"
log.workspace = true
mime = "0.3"
obfstr = "0.4.3"
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
rquickjs = { version = "0.9", features = ["rust-alloc"], default-features = false, optional = true }
rust_decimal.workspace = true
rust_decimal_macros.workspace = true
senax-common.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
utoipa = { workspace = true, features = ["actix_extras"] }
v8 = { version = "136.0.0", optional = true }
validator.workspace = true
@{-"\n"}@