[package]
name = "_repo_@{ db|snake }@_@{ group|snake }@"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
domain = { path = "../../../../1_domain" }
db = { package = "_db_@{ db|snake }@", path = "../../base" }

ahash.workspace = true
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
chrono.workspace = true
derive-new.workspace = true
futures.workspace = true
log.workspace = true
rust_decimal.workspace = true
senax-common.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
uuid.workspace = true
@%- if act_as_session %@
arc-swap = "1.5.1"
crossbeam = "0.8"
fxhash = "0.2"
once_cell.workspace = true
@%- endif %@
@{-"\n"}@