[package]
name = "db_@{ db|snake }@_repositories"
version = "0.0.0"
edition = "2024"
publish = false

[features]
cache_update_only = [ "db/cache_update_only"@%- for (name, (_, defs)) in groups %@, "_db_@{ db|snake }@_@{ name|snake }@/cache_update_only"@%- endfor %@ ]

[dependencies]
db = { package = "db_@{ db|snake }@", path = ".." }
@%- for (name, (_, defs)) in groups %@
_db_@{ db|snake }@_@{ name|snake }@ = { path = "@{ name|snake }@" }
@%- endfor %@
@{-"\n"}@