[package]
name = "base_domain"
version = "0.0.0"
edition = "2024"
publish = false

[features]
mock = ["mockall"]

[dependencies]
user_defined_types = { path = "../user_defined_types" }
anyhow.workspace = true
async-graphql.workspace = true
base64.workspace = true
chrono.workspace = true
ciborium.workspace = true
derive_more.workspace = true
downcast-rs = "2"
dyn-clone = "1.0.11"
like = "0.3.1"
mockall = {version = "0.13", optional = true}
rust_decimal.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
strum.workspace = true
strum_macros.workspace = true
utoipa.workspace = true
uuid.workspace = true
validator.workspace = true

[dev-dependencies]
mockall = "0.13"
@{-"\n"}@