[package]
name = "_base_filter_@{ db|snake }@_@{ unified_name }@"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
domain = { path = "../../../../1_domain" }
db = { package = "_db_@{ db|snake }@", path = "../../base" }

ahash.workspace = true
anyhow.workspace = true
chrono.workspace = true
fxhash = "0.2"
log.workspace = true
regex.workspace = true
rust_decimal.workspace = true
senax-common.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
@{-"\n"}@