[package]
name = "_db_@{ db|snake }@"
version = "0.0.0"
edition = "2024"
publish = false

[features]
etcd = [ "senax-common/etcd" ]
seed_schema = [ "schemars" ]

[dependencies]
@%- if !config.exclude_from_domain %@
base_domain = { path = "../../../1_domain/base_domain" }
user_defined_types = { path = "../../../1_domain/user_defined_types" }
@%- endif %@
@%- for db in config.outer_db() %@
db_@{ db|snake }@ = { package="_db_@{ db|snake }@", path = "../../@{ db|snake }@/base" }
@%- endfor %@

ahash.workspace = true
anyhow.workspace = true
arc-swap = "1.5.1"
async-stream.workspace = true
async-trait.workspace = true
bytes = "1.4"
chrono.workspace = true
crossbeam = "0.8"
derive_more.workspace = true
derive-new.workspace = true
futures.workspace = true
fxhash = "0.2"
indexmap = "2"
log.workspace = true
num-traits = "0.2"
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
rust_decimal.workspace = true
schemars = { workspace = true, optional = true }
senax-common.workspace = true
senax-encoder.workspace = true
senax-macros.workspace = true
serde.workspace = true
serde_bytes = "0.11.12"
serde_json.workspace = true
serde_repr.workspace = true
serde_yaml.workspace = true
sqlx = { workspace = true, features = ["@{ config.db }@"] }
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url = "2.2.2"
uuid.workspace = true
validator.workspace = true
zstd = "0.13"
@{-"\n"}@